### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by AnandaRisyad** [lazerbeamMe/PostgreMC#1]
none single binary file was found

**Bugs**
**Bugs**
**Bugs**
**Bugs**
**Bugs**
**Bugs**
**Bugs**
**Bugs**
**Bugs**
**Bugs**
**Bugs**
**Bugs**
**Bugs**
**Bugs**
**Bugs**
**Bugs**
**Bugs**
**Bugs**
**Bugs**
**Bugs**
**Bugs**

**Comment by lazerbeamMe** [comment]
yes, I will complete this one in the next few months. I have another private project to do
